[tool]
id = "com.dailyhobbyist.stopwatch"
label = "Stopwatch"
versionCode = 28
versionName = "5.5.7"
permissions = []
# change to com.thelightphone.sdk.emulator if you run in the SDK emulator
serverPackage = "com.lightos"
